version: '3'

services:
  db:
    image: postgres
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/data/postgresql:/var/lib/postgresql/data
